// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: payment.proto
#ifndef GRPC_payment_2eproto__INCLUDED
#define GRPC_payment_2eproto__INCLUDED

#include "payment.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace payment {

// The payment service definition.  
class PaymentService final {
 public:
  static constexpr char const* service_full_name() {
    return "payment.PaymentService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // ProcessPayment processes a payment request  
    virtual ::grpc::Status ProcessPayment(::grpc::ClientContext* context, const ::payment::PaymentRequest& request, ::payment::PaymentResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::payment::PaymentResponse>> AsyncProcessPayment(::grpc::ClientContext* context, const ::payment::PaymentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::payment::PaymentResponse>>(AsyncProcessPaymentRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::payment::PaymentResponse>> PrepareAsyncProcessPayment(::grpc::ClientContext* context, const ::payment::PaymentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::payment::PaymentResponse>>(PrepareAsyncProcessPaymentRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // ProcessPayment processes a payment request  
      virtual void ProcessPayment(::grpc::ClientContext* context, const ::payment::PaymentRequest* request, ::payment::PaymentResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ProcessPayment(::grpc::ClientContext* context, const ::payment::PaymentRequest* request, ::payment::PaymentResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::payment::PaymentResponse>* AsyncProcessPaymentRaw(::grpc::ClientContext* context, const ::payment::PaymentRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::payment::PaymentResponse>* PrepareAsyncProcessPaymentRaw(::grpc::ClientContext* context, const ::payment::PaymentRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ProcessPayment(::grpc::ClientContext* context, const ::payment::PaymentRequest& request, ::payment::PaymentResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::payment::PaymentResponse>> AsyncProcessPayment(::grpc::ClientContext* context, const ::payment::PaymentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::payment::PaymentResponse>>(AsyncProcessPaymentRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::payment::PaymentResponse>> PrepareAsyncProcessPayment(::grpc::ClientContext* context, const ::payment::PaymentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::payment::PaymentResponse>>(PrepareAsyncProcessPaymentRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ProcessPayment(::grpc::ClientContext* context, const ::payment::PaymentRequest* request, ::payment::PaymentResponse* response, std::function<void(::grpc::Status)>) override;
      void ProcessPayment(::grpc::ClientContext* context, const ::payment::PaymentRequest* request, ::payment::PaymentResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::payment::PaymentResponse>* AsyncProcessPaymentRaw(::grpc::ClientContext* context, const ::payment::PaymentRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::payment::PaymentResponse>* PrepareAsyncProcessPaymentRaw(::grpc::ClientContext* context, const ::payment::PaymentRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ProcessPayment_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // ProcessPayment processes a payment request  
    virtual ::grpc::Status ProcessPayment(::grpc::ServerContext* context, const ::payment::PaymentRequest* request, ::payment::PaymentResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ProcessPayment : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ProcessPayment() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ProcessPayment() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessPayment(::grpc::ServerContext* /*context*/, const ::payment::PaymentRequest* /*request*/, ::payment::PaymentResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcessPayment(::grpc::ServerContext* context, ::payment::PaymentRequest* request, ::grpc::ServerAsyncResponseWriter< ::payment::PaymentResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ProcessPayment<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ProcessPayment : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ProcessPayment() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::payment::PaymentRequest, ::payment::PaymentResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::payment::PaymentRequest* request, ::payment::PaymentResponse* response) { return this->ProcessPayment(context, request, response); }));}
    void SetMessageAllocatorFor_ProcessPayment(
        ::grpc::MessageAllocator< ::payment::PaymentRequest, ::payment::PaymentResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::payment::PaymentRequest, ::payment::PaymentResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ProcessPayment() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessPayment(::grpc::ServerContext* /*context*/, const ::payment::PaymentRequest* /*request*/, ::payment::PaymentResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ProcessPayment(
      ::grpc::CallbackServerContext* /*context*/, const ::payment::PaymentRequest* /*request*/, ::payment::PaymentResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ProcessPayment<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ProcessPayment : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ProcessPayment() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ProcessPayment() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessPayment(::grpc::ServerContext* /*context*/, const ::payment::PaymentRequest* /*request*/, ::payment::PaymentResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ProcessPayment : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ProcessPayment() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ProcessPayment() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessPayment(::grpc::ServerContext* /*context*/, const ::payment::PaymentRequest* /*request*/, ::payment::PaymentResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcessPayment(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ProcessPayment : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ProcessPayment() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ProcessPayment(context, request, response); }));
    }
    ~WithRawCallbackMethod_ProcessPayment() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessPayment(::grpc::ServerContext* /*context*/, const ::payment::PaymentRequest* /*request*/, ::payment::PaymentResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ProcessPayment(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ProcessPayment : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ProcessPayment() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::payment::PaymentRequest, ::payment::PaymentResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::payment::PaymentRequest, ::payment::PaymentResponse>* streamer) {
                       return this->StreamedProcessPayment(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ProcessPayment() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ProcessPayment(::grpc::ServerContext* /*context*/, const ::payment::PaymentRequest* /*request*/, ::payment::PaymentResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedProcessPayment(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::payment::PaymentRequest,::payment::PaymentResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ProcessPayment<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ProcessPayment<Service > StreamedService;
};

}  // namespace payment


#endif  // GRPC_payment_2eproto__INCLUDED
