// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: payment.proto

#include "payment.pb.h"
#include "payment.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace payment {

static const char* PaymentService_method_names[] = {
  "/payment.PaymentService/ProcessPayment",
};

std::unique_ptr< PaymentService::Stub> PaymentService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PaymentService::Stub> stub(new PaymentService::Stub(channel, options));
  return stub;
}

PaymentService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ProcessPayment_(PaymentService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status PaymentService::Stub::ProcessPayment(::grpc::ClientContext* context, const ::payment::PaymentRequest& request, ::payment::PaymentResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::payment::PaymentRequest, ::payment::PaymentResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ProcessPayment_, context, request, response);
}

void PaymentService::Stub::async::ProcessPayment(::grpc::ClientContext* context, const ::payment::PaymentRequest* request, ::payment::PaymentResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::payment::PaymentRequest, ::payment::PaymentResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ProcessPayment_, context, request, response, std::move(f));
}

void PaymentService::Stub::async::ProcessPayment(::grpc::ClientContext* context, const ::payment::PaymentRequest* request, ::payment::PaymentResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ProcessPayment_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::payment::PaymentResponse>* PaymentService::Stub::PrepareAsyncProcessPaymentRaw(::grpc::ClientContext* context, const ::payment::PaymentRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::payment::PaymentResponse, ::payment::PaymentRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ProcessPayment_, context, request);
}

::grpc::ClientAsyncResponseReader< ::payment::PaymentResponse>* PaymentService::Stub::AsyncProcessPaymentRaw(::grpc::ClientContext* context, const ::payment::PaymentRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncProcessPaymentRaw(context, request, cq);
  result->StartCall();
  return result;
}

PaymentService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PaymentService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PaymentService::Service, ::payment::PaymentRequest, ::payment::PaymentResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PaymentService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::payment::PaymentRequest* req,
             ::payment::PaymentResponse* resp) {
               return service->ProcessPayment(ctx, req, resp);
             }, this)));
}

PaymentService::Service::~Service() {
}

::grpc::Status PaymentService::Service::ProcessPayment(::grpc::ServerContext* context, const ::payment::PaymentRequest* request, ::payment::PaymentResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace payment

