// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

#include "payment.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace payment {

inline constexpr PaymentResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        success_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PaymentResponse::PaymentResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PaymentResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PaymentResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PaymentResponseDefaultTypeInternal() {}
  union {
    PaymentResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PaymentResponseDefaultTypeInternal _PaymentResponse_default_instance_;

inline constexpr PaymentRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : credit_card_number_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        user_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        total_charge_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PaymentRequest::PaymentRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PaymentRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PaymentRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PaymentRequestDefaultTypeInternal() {}
  union {
    PaymentRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PaymentRequestDefaultTypeInternal _PaymentRequest_default_instance_;
}  // namespace payment
static ::_pb::Metadata file_level_metadata_payment_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_payment_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_payment_2eproto = nullptr;
const ::uint32_t TableStruct_payment_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::payment::PaymentRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::payment::PaymentRequest, _impl_.credit_card_number_),
    PROTOBUF_FIELD_OFFSET(::payment::PaymentRequest, _impl_.total_charge_),
    PROTOBUF_FIELD_OFFSET(::payment::PaymentRequest, _impl_.user_name_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::payment::PaymentResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::payment::PaymentResponse, _impl_.success_),
    PROTOBUF_FIELD_OFFSET(::payment::PaymentResponse, _impl_.message_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::payment::PaymentRequest)},
        {11, -1, -1, sizeof(::payment::PaymentResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::payment::_PaymentRequest_default_instance_._instance,
    &::payment::_PaymentResponse_default_instance_._instance,
};
const char descriptor_table_protodef_payment_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\rpayment.proto\022\007payment\"U\n\016PaymentReque"
    "st\022\032\n\022credit_card_number\030\001 \001(\t\022\024\n\014total_"
    "charge\030\002 \001(\002\022\021\n\tuser_name\030\003 \001(\t\"3\n\017Payme"
    "ntResponse\022\017\n\007success\030\001 \001(\010\022\017\n\007message\030\002"
    " \001(\t2U\n\016PaymentService\022C\n\016ProcessPayment"
    "\022\027.payment.PaymentRequest\032\030.payment.Paym"
    "entResponseb\006proto3"
};
static ::absl::once_flag descriptor_table_payment_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_payment_2eproto = {
    false,
    false,
    259,
    descriptor_table_protodef_payment_2eproto,
    "payment.proto",
    &descriptor_table_payment_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_payment_2eproto::offsets,
    file_level_metadata_payment_2eproto,
    file_level_enum_descriptors_payment_2eproto,
    file_level_service_descriptors_payment_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_payment_2eproto_getter() {
  return &descriptor_table_payment_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_payment_2eproto(&descriptor_table_payment_2eproto);
namespace payment {
// ===================================================================

class PaymentRequest::_Internal {
 public:
};

PaymentRequest::PaymentRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:payment.PaymentRequest)
}
inline PROTOBUF_NDEBUG_INLINE PaymentRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : credit_card_number_(arena, from.credit_card_number_),
        user_name_(arena, from.user_name_),
        _cached_size_{0} {}

PaymentRequest::PaymentRequest(
    ::google::protobuf::Arena* arena,
    const PaymentRequest& from)
    : ::google::protobuf::Message(arena) {
  PaymentRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.total_charge_ = from._impl_.total_charge_;

  // @@protoc_insertion_point(copy_constructor:payment.PaymentRequest)
}
inline PROTOBUF_NDEBUG_INLINE PaymentRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : credit_card_number_(arena),
        user_name_(arena),
        _cached_size_{0} {}

inline void PaymentRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.total_charge_ = {};
}
PaymentRequest::~PaymentRequest() {
  // @@protoc_insertion_point(destructor:payment.PaymentRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PaymentRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.credit_card_number_.Destroy();
  _impl_.user_name_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void PaymentRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:payment.PaymentRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.credit_card_number_.ClearToEmpty();
  _impl_.user_name_.ClearToEmpty();
  _impl_.total_charge_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* PaymentRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 58, 2> PaymentRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_PaymentRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string credit_card_number = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(PaymentRequest, _impl_.credit_card_number_)}},
    // float total_charge = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 63, 0, PROTOBUF_FIELD_OFFSET(PaymentRequest, _impl_.total_charge_)}},
    // string user_name = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(PaymentRequest, _impl_.user_name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string credit_card_number = 1;
    {PROTOBUF_FIELD_OFFSET(PaymentRequest, _impl_.credit_card_number_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // float total_charge = 2;
    {PROTOBUF_FIELD_OFFSET(PaymentRequest, _impl_.total_charge_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // string user_name = 3;
    {PROTOBUF_FIELD_OFFSET(PaymentRequest, _impl_.user_name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\26\22\0\11\0\0\0\0"
    "payment.PaymentRequest"
    "credit_card_number"
    "user_name"
  }},
};

::uint8_t* PaymentRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:payment.PaymentRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string credit_card_number = 1;
  if (!this->_internal_credit_card_number().empty()) {
    const std::string& _s = this->_internal_credit_card_number();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "payment.PaymentRequest.credit_card_number");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // float total_charge = 2;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_total_charge = this->_internal_total_charge();
  ::uint32_t raw_total_charge;
  memcpy(&raw_total_charge, &tmp_total_charge, sizeof(tmp_total_charge));
  if (raw_total_charge != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        2, this->_internal_total_charge(), target);
  }

  // string user_name = 3;
  if (!this->_internal_user_name().empty()) {
    const std::string& _s = this->_internal_user_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "payment.PaymentRequest.user_name");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:payment.PaymentRequest)
  return target;
}

::size_t PaymentRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:payment.PaymentRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string credit_card_number = 1;
  if (!this->_internal_credit_card_number().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_credit_card_number());
  }

  // string user_name = 3;
  if (!this->_internal_user_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_user_name());
  }

  // float total_charge = 2;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_total_charge = this->_internal_total_charge();
  ::uint32_t raw_total_charge;
  memcpy(&raw_total_charge, &tmp_total_charge, sizeof(tmp_total_charge));
  if (raw_total_charge != 0) {
    total_size += 5;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData PaymentRequest::_class_data_ = {
    PaymentRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* PaymentRequest::GetClassData() const {
  return &_class_data_;
}

void PaymentRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<PaymentRequest*>(&to_msg);
  auto& from = static_cast<const PaymentRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:payment.PaymentRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_credit_card_number().empty()) {
    _this->_internal_set_credit_card_number(from._internal_credit_card_number());
  }
  if (!from._internal_user_name().empty()) {
    _this->_internal_set_user_name(from._internal_user_name());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_total_charge = from._internal_total_charge();
  ::uint32_t raw_total_charge;
  memcpy(&raw_total_charge, &tmp_total_charge, sizeof(tmp_total_charge));
  if (raw_total_charge != 0) {
    _this->_internal_set_total_charge(from._internal_total_charge());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PaymentRequest::CopyFrom(const PaymentRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:payment.PaymentRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool PaymentRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* PaymentRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void PaymentRequest::InternalSwap(PaymentRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.credit_card_number_, &other->_impl_.credit_card_number_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.user_name_, &other->_impl_.user_name_, arena);
        swap(_impl_.total_charge_, other->_impl_.total_charge_);
}

::google::protobuf::Metadata PaymentRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_payment_2eproto_getter, &descriptor_table_payment_2eproto_once,
      file_level_metadata_payment_2eproto[0]);
}
// ===================================================================

class PaymentResponse::_Internal {
 public:
};

PaymentResponse::PaymentResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:payment.PaymentResponse)
}
inline PROTOBUF_NDEBUG_INLINE PaymentResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : message_(arena, from.message_),
        _cached_size_{0} {}

PaymentResponse::PaymentResponse(
    ::google::protobuf::Arena* arena,
    const PaymentResponse& from)
    : ::google::protobuf::Message(arena) {
  PaymentResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.success_ = from._impl_.success_;

  // @@protoc_insertion_point(copy_constructor:payment.PaymentResponse)
}
inline PROTOBUF_NDEBUG_INLINE PaymentResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void PaymentResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.success_ = {};
}
PaymentResponse::~PaymentResponse() {
  // @@protoc_insertion_point(destructor:payment.PaymentResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PaymentResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.message_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void PaymentResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:payment.PaymentResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.success_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* PaymentResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 39, 2> PaymentResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_PaymentResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(PaymentResponse, _impl_.message_)}},
    // bool success = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(PaymentResponse, _impl_.success_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(PaymentResponse, _impl_.success_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool success = 1;
    {PROTOBUF_FIELD_OFFSET(PaymentResponse, _impl_.success_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(PaymentResponse, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\27\0\7\0\0\0\0\0"
    "payment.PaymentResponse"
    "message"
  }},
};

::uint8_t* PaymentResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:payment.PaymentResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_success(), target);
  }

  // string message = 2;
  if (!this->_internal_message().empty()) {
    const std::string& _s = this->_internal_message();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "payment.PaymentResponse.message");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:payment.PaymentResponse)
  return target;
}

::size_t PaymentResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:payment.PaymentResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 2;
  if (!this->_internal_message().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_message());
  }

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData PaymentResponse::_class_data_ = {
    PaymentResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* PaymentResponse::GetClassData() const {
  return &_class_data_;
}

void PaymentResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<PaymentResponse*>(&to_msg);
  auto& from = static_cast<const PaymentResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:payment.PaymentResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PaymentResponse::CopyFrom(const PaymentResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:payment.PaymentResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool PaymentResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* PaymentResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void PaymentResponse::InternalSwap(PaymentResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
        swap(_impl_.success_, other->_impl_.success_);
}

::google::protobuf::Metadata PaymentResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_payment_2eproto_getter, &descriptor_table_payment_2eproto_once,
      file_level_metadata_payment_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace payment
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
