#!/bin/bash
export MY_GRPC_PATH="/opt/gRPC/"
export PATH="${MY_GRPC_PATH}/bin:$PATH"
export LD_LIBRARY_PATH="${MY_GRPC_PATH}/lib:$LD_LIBRARY_PATH"
export C_INCLUDE_PATH="${MY_GRPC_PATH}/include:$C_INCLUDE_PATH"
export CPLUS_INCLUDE_PATH="${MY_GRPC_PATH}/include:$CPLUS_INCLUDE_PATH"
